### ISSUE TITLE
LGPLv3 and static linking

### ISSUE THREAD

**Issue by janflyborg** [go-xmlpath/xmlpath#30]
I would love to use this library in the closed source application that the company I work for is building, but since LGPL forces me to either open source our code base or link dynamically with a library that is already present on the user's machine, I don't think it is possible to use your work.

So what is the reasoning behind licensing it as  LGPLv3? Or do you simply only want people who build open source to use this library?

**Comment by zhengchun** [comment]
you can try this repository [xquery](https://github.com/antchfx/xquery), support XPath query for XML.

**Comment by janflyborg** [comment]
Thanks for this. I will look into it.

**Comment by Seb-C** [comment]
I also would be interested to use this in an open source project and it seems that I cannot do that unless I also licence my work in LGPL, which I refuse to do (planning to use MIT).
What a shame.

**Comment by Seb-C** [comment]
@zhengchun Thanks for your package, I will use it :+1:

**Comment by niemeyer** [comment]
Out of curiosity, has anyone complaining here actually read the license?
